# filters2 = list(['~opentop2-speedup1-~speedup2-~jump2-foot0-~small_capq-minute-2', '~jump1-jump2-foot1-foot2-~isnew-~small_capq-small_volume-~opentop1-top1-2', '~speedup1-~jump1-speedup2-foot0-foot1-~isnew-~small_capq-2', '~opentop2-~jump2-~foot0-~foot2-isnew-small_volume-2', 'speedup1-~jump1-speedup2-~foot1-~foot2-~isnew-small_capq-small_volume-2', '~opentop2-~speedup1-~speedup2-foot1-~foot2-isnew-minute-2', '~opentop2-speedup1-foot1-foot2-small_capq-small_volume-2', '~opentop2-~speedup1-jump1-jump2-~foot1-small_volume-2'])
# #8 182 2
# #--------
# filters3 = list(['jump1-~foot1-~foot2-~isnew-minute-small_volume-yz0-3', '~opentop2-~jump1-~jump2-foot0-~foot2-~isnew-small_capq-minute-3', 'jump1-~foot1-~isnew-small_capq-minute-small_volume-yz0-3', '~speedup1-jump1-~speedup2-~jump2-~foot1-~foot2-minute-~small_volume-~opentop0-top0-~opentop1-top1-3', '~opentop2-~speedup1-jump2-foot0-~foot1-minute-small_volume-~opentop1-top1-3', 'jump2-foot0-~foot1-foot2-~isnew-small_capq-small_volume-3', '~opentop2-~speedup2-jump2-foot0-~foot1-~foot2-small_capq-~small_volume-3', '~opentop2-jump1-jump2-~foot1-foot2-~small_capq-minute-~opentop1-top1-3', '~opentop2-~jump1-~jump2-~foot0-~foot1-~small_capq-minute-3', 'opentop2-~speedup1-jump1-~foot1-~foot2-small_volume-~opentop1-top1-3', '~opentop2-speedup1-foot0-~foot2-~isnew-~small_capq-small_volume-3', 'jump1-speedup2-foot1-~isnew-small_capq-small_volume-~opentop0-top0-~opentop1-top1-3', 'opentop2-jump1-jump2-foot1-minute-~opentop1-top1-3', '~opentop2-jump2-foot0-~foot1-~foot2-~small_capq-small_volume-3', '~speedup1-speedup2-foot0-~foot1-~isnew-small_capq-small_volume-~opentop1-top1-3', '~speedup1-jump1-~jump2-foot0-~foot1-minute-~yz1-top1-opentop1-3', '~opentop2-speedup1-jump1-jump2-~foot1-foot2-~small_capq-~opentop1-top1-3', '~opentop2-~speedup1-foot0-~foot1-~foot2-minute-~small_volume-~yz1-top1-opentop1-3'])
# #18 2396 3
# #--------
# filters4 = list(['~opentop2-~speedup1-~foot2-~isnew-~small_capq-minute-small_volume-~opentop1-top1-4', '~opentop2-~speedup1-~jump2-~foot1-~foot2-small_capq-small_volume-~opentop0-top0-4', '~opentop2-jump1-~speedup2-~foot1-minute-small_volume-~yz1-top1-opentop1-4', '~speedup1-jump1-~speedup2-~foot0-~foot2-~isnew-minute-~opentop0-top0-4', '~speedup1-jump1-jump2-~foot1-foot2-small_volume-4', '~opentop2-~speedup1-jump1-~speedup2-~foot1-~foot2-~small_capq-minute-4', '~opentop2-jump2-~foot1-~isnew-small_volume-yz0-4', '~opentop2-~speedup1-jump1-~speedup2-~foot1-minute-small_volume-4', '~opentop2-~speedup1-jump1-foot0-~foot1-minute-small_volume-4', '~opentop2-~jump1-speedup2-small_capq-small_volume-~opentop1-top1-4', '~speedup1-foot0-~foot1-foot2-small_volume-4', '~speedup1-~jump2-~foot1-~isnew-small_capq-minute-small_volume-4', '~opentop2-~foot1-~isnew-small_capq-minute-small_volume-yz0-4', '~opentop2-~speedup2-~foot0-~isnew-small_capq-minute-small_volume-~opentop0-top0-4', '~opentop2-jump1-~speedup2-~isnew-minute-small_volume-~yz1-top1-opentop1-4', '~opentop2-~speedup1-jump1-minute-small_volume-~yz1-top1-opentop1-4', '~opentop2-jump2-foot2-small_capq-small_volume-4', '~opentop2-speedup2-foot2-small_capq-minute-~opentop1-top1-4'])
# #18 4554 4
# #--------
# filters5 = list(['jump1-~speedup2-~foot2-~isnew-minute-~yz1-top1-opentop1-5', '~speedup1-~speedup2-~foot0-minute-~small_volume-~opentop1-top1-5', '~jump1-~speedup2-~foot1-~isnew-~opentop1-top1-5', 'speedup1-jump1-~speedup2-~foot0-~foot2-small_volume-~opentop0-top0-5', '~opentop2-~speedup1-~jump1-~foot1-5'])
# #5 379 5
# #--------
# filters6 = list(['~opentop2-jump1-small_capq-minute-small_volume-6', '~opentop2-~speedup1-foot0-~foot1-small_capq-minute-6', 'jump1-~speedup2-~foot2-~isnew-small_capq-minute-small_volume-6'])
# #3 582 6
# #--------
# filters7 = list(['~foot2-small_volume-yz0-7'])
# #1 29 7
#--------

filters2 = ['~opentop2-speedup1-~speedup2-~jump2-foot0-~small_capq-minute-2', '~jump1-jump2-foot1-foot2-~isnew-~small_capq-small_volume-~opentop1-2', '~speedup1-~jump1-speedup2-foot0-foot1-~small_capq-2', '~opentop2-~jump2-~foot0-~foot2-isnew-small_volume-2', 'speedup1-~jump1-speedup2-~foot1-~foot2-~isnew-small_capq-small_volume-2', '~opentop2-~speedup1-~speedup2-foot1-isnew-minute-2', '~opentop2-speedup1-foot1-foot2-small_volume-2', '~opentop2-~speedup1-jump1-jump2-~foot1-small_volume-2']
filters3 = ['~foot1-small_volume-yz0-3', '~opentop2-~jump1-~jump2-foot0-~isnew-small_capq-minute-3', 'jump1-~foot1-minute-small_volume-yz0-3', '~speedup1-jump1-~speedup2-~jump2-~foot1-~foot2-minute-~small_volume-~opentop0-~opentop1-3', '~opentop2-~speedup1-jump2-foot0-~foot1-minute-small_volume-~opentop1-3', 'jump2-foot0-~foot1-foot2-small_capq-small_volume-3', '~opentop2-~speedup2-jump2-foot0-~foot1-~foot2-small_capq-~small_volume-3', '~opentop2-jump1-jump2-~foot1-foot2-~small_capq-minute-~opentop1-3', '~opentop2-~jump1-~jump2-~foot0-~foot1-~small_capq-minute-3', 'opentop2-~speedup1-jump1-~foot1-~foot2-~opentop1-3', '~opentop2-speedup1-foot0-~foot2-~small_capq-small_volume-3', 'jump1-speedup2-foot1-~isnew-small_capq-small_volume-~opentop0-~opentop1-3', 'opentop2-jump1-jump2-foot1-minute-~opentop1-3', '~opentop2-jump2-foot0-~foot1-~foot2-~small_capq-small_volume-3', '~speedup1-speedup2-foot0-~foot1-~isnew-small_capq-small_volume-~opentop1-3', '~speedup1-jump1-~jump2-foot0-~foot1-minute-opentop1-3', '~opentop2-speedup1-jump1-jump2-~foot1-foot2-~small_capq-~opentop1-3', '~opentop2-~speedup1-foot0-~foot1-~foot2-minute-~small_volume-opentop1-3']
filters4 = ['~opentop2-~speedup1-~foot2-~isnew-~small_capq-minute-small_volume-~opentop1-4', '~speedup1-~jump2-~foot1-small_capq-small_volume-top0-4', '~opentop2-jump1-minute-small_volume-opentop1-4', '~speedup1-jump1-~speedup2-~foot0-~foot2-~isnew-minute-~opentop0-4', '~speedup1-jump1-jump2-~foot1-foot2-small_volume-4', '~opentop2-~speedup1-jump1-~speedup2-~foot1-~foot2-~small_capq-minute-4', '~opentop2-small_volume-yz0-4', '~opentop2-~speedup1-jump1-~speedup2-~foot1-minute-small_volume-4', '~opentop2-~speedup1-jump1-foot0-~foot1-minute-small_volume-4', '~opentop2-~jump1-speedup2-small_capq-small_volume-~opentop1-4', '~speedup1-foot0-~foot1-foot2-small_volume-4', '~speedup1-~jump2-~foot1-small_capq-minute-small_volume-4', '~opentop2-~foot1-small_capq-minute-small_volume-yz0-4', '~opentop2-~speedup2-~foot0-small_capq-minute-small_volume-~opentop0-top0-4', '~opentop2-jump1-minute-small_volume-~yz1-opentop1-4', '~opentop2-jump1-minute-small_volume-~yz1-4', '~opentop2-jump2-foot2-small_capq-small_volume-4', '~opentop2-speedup2-foot2-small_capq-minute-4']
filters5 = ['jump1-~speedup2-~foot2-~isnew-minute-~yz1-opentop1-5', '~speedup1-~speedup2-~foot0-minute-~small_volume-~opentop1-5', '~jump1-~speedup2-~foot1-~isnew-~opentop1-5', 'speedup1-~speedup2-~foot0-~foot2-small_volume-~opentop0-5', '~opentop2-~speedup1-~jump1-~foot1-5']
filters6 = ['~opentop2-jump1-small_capq-minute-small_volume-6', '~opentop2-foot0-small_capq-minute-6', '~speedup2-~foot2-~isnew-small_capq-minute-small_volume-6']
filters7 = ['~foot2-small_volume-yz0-7']


filterss = [filters2,filters3,filters4,filters5,filters6,filters7]



# filters2 = ['~speedup1-~jump1-speedup2-foot0-foot1-~small_capq-2']
# filters3 = ['~foot1-small_volume-yz0-3', 'jump1-~foot1-minute-small_volume-yz0-3', 'jump2-foot0-~foot1-foot2-small_capq-small_volume-3', 'opentop2-~speedup1-jump1-~foot1-~foot2-~opentop1-3', '~opentop2-speedup1-foot0-~foot2-~small_capq-small_volume-3', 'opentop2-jump1-jump2-foot1-minute-~opentop1-3', '~opentop2-jump2-foot0-~foot1-~foot2-~small_capq-small_volume-3']
# filters4 = ['~opentop2-~speedup1-~foot2-~isnew-~small_capq-minute-small_volume-~opentop1-4', '~speedup1-~jump2-~foot1-small_capq-small_volume-top0-4', '~speedup1-jump1-jump2-~foot1-foot2-small_volume-4', '~opentop2-~speedup1-jump1-~speedup2-~foot1-minute-small_volume-4', '~opentop2-~speedup1-jump1-foot0-~foot1-minute-small_volume-4', '~opentop2-~jump1-speedup2-small_capq-small_volume-~opentop1-4', '~speedup1-foot0-~foot1-foot2-small_volume-4', '~speedup1-~jump2-~foot1-small_capq-minute-small_volume-4', '~opentop2-~foot1-small_capq-minute-small_volume-yz0-4', '~opentop2-~speedup2-~foot0-small_capq-minute-small_volume-~opentop0-top0-4', '~opentop2-jump1-minute-small_volume-~yz1-opentop1-4', '~opentop2-jump2-foot2-small_capq-small_volume-4', '~opentop2-speedup2-foot2-small_capq-minute-4']
# filters5 = ['jump1-~speedup2-~foot2-~isnew-minute-~yz1-opentop1-5']
# filters6 = ['~opentop2-jump1-small_capq-minute-small_volume-6', '~opentop2-foot0-small_capq-minute-6']
# filters7 = []

# filterss = [filters2,filters3,filters4,filters5,filters6]
