# filters2 = list(['~opentop2-~speedup1-jump1-jump2-~foot1-~isnew-minute-small_volume-2', '~opentop2-small_volume-yz1-2', 'opentop2-~speedup1-~jump1-~speedup2-foot0-~foot1-small_capq-minute-2', '~opentop2-speedup1-~jump1-foot0-~foot2-~small_capq-minute-2', '~opentop2-speedup1-jump2-foot1-foot2-minute-small_volume-~opentop1-top1-2', 'opentop2-foot0-foot1-~small_volume-2', 'speedup1-speedup2-jump2-foot0-~foot2-~isnew-small_capq-small_volume-2', '~jump1-jump2-~foot0-~foot1-~yz1-top1-opentop1-2', '~opentop2-speedup1-~jump1-jump2-foot0-~foot2-~isnew-small_volume-~opentop1-top1-2', '~speedup1-~jump1-speedup2-foot0-foot1-~isnew-~small_capq-minute-2', '~opentop2-~speedup1-~speedup2-foot1-~foot2-isnew-minute-2', '~opentop2-~jump2-~foot0-~foot2-isnew-small_volume-2', '~opentop2-~speedup1-~jump1-speedup2-~foot0-foot1-~small_capq-small_volume-2'])
# #13 291 2
# #--------
# filters3 = list(['~speedup1-jump1-foot0-~foot1-foot2-small_capq-minute-~opentop1-top1-3', '~speedup1-~speedup2-foot0-~foot1-~foot2-small_capq-minute-~small_volume-~yz1-top1-opentop1-3', 'jump1-jump2-~foot0-~foot1-foot2-~small_capq-minute-~opentop1-top1-3', '~opentop2-~speedup1-jump1-speedup2-~foot1-foot2-minute-~opentop1-top1-3', 'opentop2-~speedup1-jump1-~foot1-~opentop1-top1-3', '~jump1-~foot0-~foot1-~foot2-~small_capq-small_volume-3', '~opentop2-~speedup1-~speedup2-foot1-small_capq-small_volume-~opentop1-top1-3', 'jump1-~foot1-~isnew-small_capq-minute-small_volume-yz0-~opentop1-top1-3', '~opentop2-jump2-foot0-~foot1-~foot2-~isnew-~small_capq-small_volume-3', 'jump1-~foot1-~foot2-~isnew-minute-small_volume-yz0-~opentop1-top1-3', '~opentop2-~jump2-foot0-~foot1-~foot2-small_capq-minute-small_volume-~yz1-top1-opentop1-3', '~speedup1-jump1-~jump2-foot0-~isnew-minute-~small_volume-~opentop0-top0-~opentop1-top1-3', 'opentop2-speedup1-~jump1-~foot0-~foot1-~isnew-~opentop1-top1-3', 'jump1-~speedup2-~foot1-~foot2-~isnew-minute-small_volume-yz0-3', '~opentop2-jump1-jump2-~foot1-foot2-~small_capq-minute-~opentop1-top1-3', '~opentop2-speedup1-foot0-~foot2-~isnew-~small_capq-minute-small_volume-3'])
# # 16 1270 3
# # --------
# filters4 = list(['~opentop2-~speedup1-jump1-~jump2-small_capq-minute-small_volume-~opentop0-top0-4', '~foot1-isnew-small_capq-4', '~opentop2-minute-small_volume-~yz1-top1-opentop1-4', '~speedup1-jump1-~jump2-foot0-~foot1-small_capq-minute-small_volume-4', '~speedup1-~foot0-~foot2-~isnew-~small_capq-minute-~opentop1-top1-4', '~opentop2-jump2-small_volume-yz0-4', '~opentop2-jump1-jump2-~foot0-~foot1-foot2-small_capq-4', '~opentop2-~speedup1-jump1-foot0-~foot1-~foot2-minute-small_volume-4', '~speedup1-jump1-~speedup2-~foot0-~foot1-~isnew-minute-~opentop0-top0-4', '~opentop2-~speedup1-~foot0-~foot1-foot2-small_capq-4', '~speedup1-~jump2-small_capq-minute-small_volume-~yz1-top1-opentop1-4', '~opentop2-~speedup2-jump2-foot2-small_capq-minute-4', '~opentop2-~speedup1-~speedup2-~foot1-~foot2-~small_capq-minute-4', '~opentop2-jump1-~speedup2-jump2-foot1-small_volume-4', '~speedup1-~speedup2-foot0-minute-small_volume-~yz1-top1-opentop1-4', '~speedup1-jump1-~speedup2-~foot0-~isnew-small_capq-small_volume-~opentop0-top0-~opentop1-top1-4', '~opentop2-jump1-~speedup2-~foot1-~isnew-small_capq-minute-small_volume-yz0-4', '~opentop2-~speedup2-jump2-~foot0-small_capq-small_volume-4'])
# # 18 3927 4
# # --------
# filters5 = list(['~opentop2-~speedup1-~jump2-foot0-~foot2-small_capq-small_volume-5', '~jump2-foot0-~foot1-~foot2-~isnew-minute-small_volume-~yz1-top1-opentop1-5', 'jump1-~foot0-~foot1-~foot2-~isnew-minute-~yz1-top1-opentop1-5', 'jump2-~foot0-~foot1-minute-small_volume-~yz0-top0-opentop0-~opentop1-top1-5', '~opentop2-~speedup1-jump1-~speedup2-~foot0-~isnew-minute-~opentop0-top0-~opentop1-top1-5', '~opentop2-~jump1-~jump2-~foot1-~foot2-small_capq-small_volume-5', '~speedup1-~jump1-speedup2-~foot0-~foot1-small_volume-~opentop1-top1-5'])
# # 7 679 5
# # --------
# filters6 = list(['~opentop2-~jump1-~speedup2-~jump2-~foot1-minute-6', 'foot0-~foot1-~foot2-~isnew-small_capq-minute-small_volume-6', '~opentop2-jump1-jump2-~foot2-minute-small_volume-6'])
# # 3 981 6
# # --------
# filters7 = list(['~opentop2-jump1-foot0-~foot1-~foot2-~isnew-small_capq-minute-7', '~opentop2-~speedup2-foot0-~foot1-~foot2-~isnew-small_capq-minute-7'])
# # 2 375 7
# # --------

filters2 = ['~opentop2-~speedup1-jump1-jump2-~foot1-~isnew-minute-small_volume-2', '~opentop2-small_volume-yz1-2', 'opentop2-~speedup1-~jump1-~speedup2-foot0-~foot1-small_capq-minute-2', '~opentop2-speedup1-~jump1-foot0-~small_capq-minute-2', '~opentop2-speedup1-jump2-foot1-foot2-minute-small_volume-~opentop1-2', 'opentop2-foot0-foot1-~small_volume-2', 'speedup1-speedup2-foot0-~foot2-~isnew-small_capq-small_volume-2', '~jump1-jump2-~foot0-~foot1-opentop1-2', '~opentop2-speedup1-~jump1-jump2-foot0-~foot2-~isnew-small_volume-~opentop1-2', '~speedup1-~jump1-speedup2-foot0-foot1-~small_capq-minute-2', '~opentop2-~speedup1-~speedup2-foot1-isnew-minute-2', '~opentop2-~jump2-~foot0-~foot2-isnew-small_volume-2', '~opentop2-~speedup1-~jump1-speedup2-~foot0-foot1-~small_capq-small_volume-2']
filters3 = ['~speedup1-jump1-foot0-~foot1-foot2-small_capq-minute-~opentop1-3', '~speedup1-~speedup2-foot0-~foot1-~foot2-small_capq-minute-~small_volume-opentop1-3', 'jump1-jump2-~foot0-~foot1-foot2-~small_capq-minute-~opentop1-3', '~opentop2-~speedup1-jump1-speedup2-~foot1-foot2-minute-~opentop1-3', 'opentop2-~speedup1-jump1-~foot1-~opentop1-3', '~jump1-~foot1-~foot2-~small_capq-small_volume-3', '~opentop2-~speedup1-~speedup2-foot1-small_capq-small_volume-~opentop1-3', 'jump1-~foot1-minute-small_volume-yz0-3', '~opentop2-jump2-foot0-~foot1-~foot2-~small_capq-small_volume-3', 'jump1-~foot1-minute-small_volume-yz0-3', '~opentop2-~jump2-foot0-~foot1-~foot2-minute-small_volume-opentop1-3', '~speedup1-jump1-~jump2-foot0-~isnew-minute-~small_volume-~opentop0-~opentop1-3', 'opentop2-speedup1-~jump1-~foot0-~foot1-~isnew-~opentop1-3', 'jump1-~foot1-minute-small_volume-yz0-3', '~opentop2-jump1-jump2-~foot1-foot2-~small_capq-minute-~opentop1-3', '~opentop2-speedup1-foot0-~foot2-~small_capq-minute-small_volume-3']
filters4 = ['~opentop2-~speedup1-jump1-~jump2-small_capq-minute-small_volume-~opentop0-4', '~foot1-isnew-4', '~opentop2-minute-small_volume-~yz1-top1-opentop1-4', '~speedup1-jump1-~jump2-foot0-~foot1-small_capq-minute-small_volume-4', '~speedup1-~foot0-~foot2-~isnew-~small_capq-minute-~opentop1-4', '~opentop2-jump2-small_volume-yz0-4', '~opentop2-jump1-jump2-~foot0-~foot1-foot2-small_capq-4', '~opentop2-~speedup1-jump1-foot0-~foot1-minute-small_volume-4', '~speedup1-jump1-~speedup2-~foot0-~foot1-~isnew-minute-~opentop0-4', '~opentop2-~speedup1-~foot0-~foot1-foot2-small_capq-4', '~speedup1-small_capq-minute-small_volume-~yz1-top1-opentop1-4', '~opentop2-~speedup2-foot2-small_capq-4', '~opentop2-~speedup1-~foot1-~foot2-~small_capq-minute-4', '~opentop2-jump1-~speedup2-jump2-foot1-small_volume-4', '~speedup1-foot0-minute-small_volume-~yz1-top1-opentop1-4', '~speedup1-jump1-~speedup2-~foot0-~isnew-small_capq-small_volume-~opentop0-~opentop1-4', 'jump1-~speedup2-~foot1-minute-small_volume-yz0-4', '~opentop2-~speedup2-jump2-~foot0-small_capq-small_volume-4']
filters5 = ['~opentop2-~speedup1-~jump2-foot0-~foot2-small_capq-small_volume-5', '~jump2-foot0-~foot2-~isnew-minute-small_volume-top1-opentop1-5', 'jump1-~foot0-~foot1-~foot2-~isnew-minute-opentop1-5', 'jump2-~foot1-small_volume-opentop0-~opentop1-5', '~opentop2-~speedup1-jump1-~speedup2-~foot0-~isnew-minute-~opentop0-~opentop1-5', '~opentop2-~jump1-~jump2-~foot1-~foot2-small_capq-small_volume-5', '~speedup1-~jump1-speedup2-~foot0-~foot1-small_volume-~opentop1-5']
filters6 = ['~opentop2-~jump1-~speedup2-~jump2-~foot1-minute-6', 'foot0-~foot1-~isnew-small_capq-minute-small_volume-6', '~opentop2-jump1-jump2-minute-small_volume-6']
filters7 = ['~opentop2-jump1-foot0-~foot1-~foot2-~isnew-small_capq-minute-7', '~opentop2-~speedup2-foot0-~foot1-~foot2-~isnew-small_capq-minute-7']

filterss = [filters2,filters3,filters4,filters5,filters6,filters7]
